apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tekton-helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: sriramhcl/python-tekton-flaksapp-2
          env:
            - name: TARGET
              value: "Python Flask Sample v1"