apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tekton-helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/sriramhcl/python-tekton-hello-world:latest
          env:
            - name: TARGET
              value: "Python Sample v1"