apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: private-repo-flask-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/sriramhcl/python-tekton-flaksapp
          env:
            - name: TARGET
              value: "Python Sample v1"